/**
 * Security-deposit return rules for all 50 states + DC.
 *
 * Compiled from state statutes; figures reflect the standard residential case.
 * Many statutes have conditions (proper notice, forwarding address, building
 * size) captured in deadlineText/notes. Every page that renders this data also
 * renders LAST_REVIEWED and a verify-the-statute disclaimer — state law changes.
 */

export const LAST_REVIEWED = "July 2026";

export interface StateLaw {
  slug: string;
  name: string;
  abbr: string;
  /** Primary statute citation, e.g. "Cal. Civ. Code §1950.5". */
  statute: string;
  /** Days used by the deadline calculator (the standard/outer case). */
  deadlineDays: number;
  /** When true, deadlineDays counts business days, not calendar days. */
  businessDays?: boolean;
  /** Human phrasing of the deadline, including conditions. */
  deadlineText: string;
  /** Clause completing: "A landlord who misses the deadline …". */
  penaltyText: string;
  /** Statutory damages multiplier for headline/stamp use (null = none). */
  multiplier: number | null;
  /** Flat statutory add-on, e.g. Texas's $100. */
  flatBonus?: number;
  /** Whether the tenant must supply a forwarding address to start the clock. */
  forwardingNote?: string;
  interest?: string;
  depositCap?: string;
  notes?: string[];
}

export const STATES: StateLaw[] = [
  {
    slug: "alabama", name: "Alabama", abbr: "AL",
    statute: "Ala. Code §35-9A-201",
    deadlineDays: 60,
    deadlineText: "60 days after the tenancy ends and you deliver possession.",
    penaltyText: "forfeits the right to keep any portion of the deposit and becomes liable for double the deposit.",
    multiplier: 2,
    forwardingNote: "Leave a forwarding address — unclaimed deposits can be forfeited after 180 days.",
  },
  {
    slug: "alaska", name: "Alaska", abbr: "AK",
    statute: "Alaska Stat. §34.03.070",
    deadlineDays: 30,
    deadlineText: "14 days if you gave proper notice before moving out; 30 days if you didn't.",
    penaltyText: "may be liable for up to twice the amount wrongfully withheld.",
    multiplier: 2,
    depositCap: "Two months' rent (where rent is under $2,000/month).",
  },
  {
    slug: "arizona", name: "Arizona", abbr: "AZ",
    statute: "Ariz. Rev. Stat. §33-1321",
    deadlineDays: 14, businessDays: true,
    deadlineText: "14 business days (roughly three weeks) after termination and demand.",
    penaltyText: "is liable for the amount wrongfully withheld plus damages of twice that amount.",
    multiplier: 2,
    depositCap: "One and one-half months' rent.",
    notes: ["You have the right to be present at the move-out inspection — request it in writing."],
  },
  {
    slug: "arkansas", name: "Arkansas", abbr: "AR",
    statute: "Ark. Code §18-16-305",
    deadlineDays: 60,
    deadlineText: "60 days after the tenancy terminates.",
    penaltyText: "is liable for double the amount wrongfully withheld, plus costs and attorney's fees.",
    multiplier: 2,
    depositCap: "Two months' rent.",
    notes: ["The deposit statute exempts landlords who own five or fewer rental units they manage themselves."],
  },
  {
    slug: "california", name: "California", abbr: "CA",
    statute: "Cal. Civ. Code §1950.5",
    deadlineDays: 21,
    deadlineText: "21 calendar days after you move out.",
    penaltyText: "can owe statutory damages of up to twice the deposit — on top of the amount due — where the deposit is retained in bad faith.",
    multiplier: 2,
    depositCap: "One month's rent (since July 2024; limited small-landlord exception at two months).",
    notes: [
      "You can request an initial pre-move-out inspection so you have a chance to fix issues first.",
      "Deductions over $125 must come with copies of receipts or invoices.",
      "Some cities (San Francisco, Berkeley, others) also require interest on deposits.",
    ],
  },
  {
    slug: "colorado", name: "Colorado", abbr: "CO",
    statute: "Colo. Rev. Stat. §38-12-103",
    deadlineDays: 30,
    deadlineText: "30 days (up to 60 only if your lease says so).",
    penaltyText: "and willfully retains the deposit is liable for treble the amount wrongfully withheld, plus attorney's fees.",
    multiplier: 3,
    notes: [
      "Before suing you must give the landlord 7 days' written notice — a demand letter like ours satisfies this requirement.",
    ],
  },
  {
    slug: "connecticut", name: "Connecticut", abbr: "CT",
    statute: "Conn. Gen. Stat. §47a-21",
    deadlineDays: 30,
    deadlineText: "30 days after you move out, or 15 days after you deliver a forwarding address — whichever is later.",
    penaltyText: "is liable for twice the amount wrongfully withheld.",
    multiplier: 2,
    interest: "Interest on the deposit is required by statute.",
    depositCap: "Two months' rent (one month if you're 62 or older).",
    forwardingNote: "Send your forwarding address in writing — it starts the 15-day clock.",
  },
  {
    slug: "delaware", name: "Delaware", abbr: "DE",
    statute: "25 Del. C. §5514",
    deadlineDays: 20,
    deadlineText: "20 days after the tenancy ends.",
    penaltyText: "is liable for double the amount wrongfully withheld.",
    multiplier: 2,
    depositCap: "One month's rent on leases of a year or more.",
  },
  {
    slug: "district-of-columbia", name: "District of Columbia", abbr: "DC",
    statute: "14 DCMR §309",
    deadlineDays: 45,
    deadlineText: "45 days after the tenancy ends (return or itemized notice of deductions).",
    penaltyText: "in bad faith is liable for double the amount withheld.",
    multiplier: 2,
    interest: "Interest on the deposit is required.",
    depositCap: "One month's rent.",
  },
  {
    slug: "florida", name: "Florida", abbr: "FL",
    statute: "Fla. Stat. §83.49",
    deadlineDays: 30,
    deadlineText: "15 days to return the deposit in full — or 30 days to send written notice (by certified mail) of intent to claim any of it.",
    penaltyText: "forfeits the right to keep any portion of the deposit if the 30-day certified notice never arrives; the prevailing party in court also recovers attorney's fees.",
    multiplier: null,
    notes: ["You then have 15 days to object in writing to any claimed deductions — object, or the landlord may deduct as noticed."],
  },
  {
    slug: "georgia", name: "Georgia", abbr: "GA",
    statute: "O.C.G.A. §44-7-34",
    deadlineDays: 30,
    deadlineText: "30 days after termination of the tenancy.",
    penaltyText: "and acts in bad faith is liable for three times the amount wrongfully withheld, plus attorney's fees.",
    multiplier: 3,
  },
  {
    slug: "hawaii", name: "Hawaii", abbr: "HI",
    statute: "Haw. Rev. Stat. §521-44",
    deadlineDays: 14,
    deadlineText: "14 days after the tenancy ends.",
    penaltyText: "forfeits the right to keep any of the deposit, and courts can award additional damages where retention was in bad faith.",
    multiplier: null,
    depositCap: "One month's rent (plus a pet deposit where allowed).",
  },
  {
    slug: "idaho", name: "Idaho", abbr: "ID",
    statute: "Idaho Code §6-321",
    deadlineDays: 21,
    deadlineText: "21 days — extendable to a maximum of 30 only if the lease says so.",
    penaltyText: "can owe up to three times the amount wrongfully withheld where the refusal was arbitrary or in bad faith.",
    multiplier: 3,
  },
  {
    slug: "illinois", name: "Illinois", abbr: "IL",
    statute: "765 ILCS 710/1",
    deadlineDays: 45,
    deadlineText: "Itemized statement within 30 days; refund within 45 days (buildings with 5+ units).",
    penaltyText: "is liable for twice the deposit plus attorney's fees.",
    multiplier: 2,
    notes: ["Chicago's RLTO is stricter still — interest is owed and penalties are routine. Cook County has its own RTLO."],
  },
  {
    slug: "indiana", name: "Indiana", abbr: "IN",
    statute: "Ind. Code §32-31-3-12",
    deadlineDays: 45,
    deadlineText: "45 days after termination and delivery of possession.",
    penaltyText: "forfeits all claims to the deposit and is liable for the tenant's attorney's fees.",
    multiplier: null,
    forwardingNote: "The clock runs from when you supply a forwarding or mailing address.",
  },
  {
    slug: "iowa", name: "Iowa", abbr: "IA",
    statute: "Iowa Code §562A.12",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends and you provide a mailing address.",
    penaltyText: "forfeits the deposit and, if acting in bad faith, can owe up to $200 in punitive damages.",
    multiplier: null,
    depositCap: "Two months' rent.",
    forwardingNote: "Provide a mailing address in writing — deposits unclaimed for a year can be forfeited.",
  },
  {
    slug: "kansas", name: "Kansas", abbr: "KS",
    statute: "Kan. Stat. §58-2550",
    deadlineDays: 30,
    deadlineText: "30 days after termination of the tenancy.",
    penaltyText: "is liable for one and one-half times the amount wrongfully withheld.",
    multiplier: 1.5,
    depositCap: "One month's rent (unfurnished); one and one-half months (furnished).",
  },
  {
    slug: "kentucky", name: "Kentucky", abbr: "KY",
    statute: "Ky. Rev. Stat. §383.580",
    deadlineDays: 60,
    deadlineText: "No single statewide deadline — the deposit statute applies only where a city or county has adopted the URLTA (Louisville, Lexington and others); 60 days is the outer bound for unclaimed deposits.",
    penaltyText: "or ignores the itemization rules forfeits the right to keep the deposit.",
    multiplier: null,
    notes: ["Where the URLTA applies, the deposit must be held in a disclosed, separate account — ask which bank holds yours."],
  },
  {
    slug: "louisiana", name: "Louisiana", abbr: "LA",
    statute: "La. Rev. Stat. §9:3251",
    deadlineDays: 30,
    deadlineText: "One month after the lease ends and you deliver possession.",
    penaltyText: "owes actual damages or $300 — whichever is greater — plus court costs and attorney's fees, where the failure is willful.",
    multiplier: null,
    forwardingNote: "You must leave a forwarding address in writing to preserve the claim.",
  },
  {
    slug: "maine", name: "Maine", abbr: "ME",
    statute: "14 M.R.S. §6033",
    deadlineDays: 30,
    deadlineText: "30 days under a written lease; 21 days for a tenancy at will.",
    penaltyText: "and wrongfully retains the deposit is liable for double the amount, plus attorney's fees.",
    multiplier: 2,
    depositCap: "Two months' rent.",
  },
  {
    slug: "maryland", name: "Maryland", abbr: "MD",
    statute: "Md. Real Prop. Code §8-203",
    deadlineDays: 45,
    deadlineText: "45 days after the tenancy ends.",
    penaltyText: "and withholds without a right to do so can owe up to three times the amount withheld, plus attorney's fees.",
    multiplier: 3,
    interest: "Interest on the deposit is required by statute.",
    depositCap: "One month's rent (as of October 2024).",
    notes: ["You can demand to be present at the move-out inspection — request it by certified mail before you leave."],
  },
  {
    slug: "massachusetts", name: "Massachusetts", abbr: "MA",
    statute: "Mass. Gen. Laws c. 186, §15B",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "is liable for triple the deposit, plus 5% interest, court costs, and attorney's fees.",
    multiplier: 3,
    interest: "5% (or the bank's actual rate) — owed yearly and at move-out.",
    depositCap: "One month's rent.",
    notes: [
      "The strictest deposit law in the country: failing to keep the deposit in a separate Massachusetts escrow account, or missing the required statements, can trigger treble damages by itself.",
    ],
  },
  {
    slug: "michigan", name: "Michigan", abbr: "MI",
    statute: "Mich. Comp. Laws §554.609",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "in bad faith is liable for double the amount wrongfully withheld.",
    multiplier: 2,
    depositCap: "One and one-half months' rent.",
    forwardingNote: "You must mail your forwarding address within 4 days of moving out — do it in writing and keep proof.",
    notes: ["If the landlord wants to keep any of it for damages, they must sue within 45 days of you moving out — or return it."],
  },
  {
    slug: "minnesota", name: "Minnesota", abbr: "MN",
    statute: "Minn. Stat. §504B.178",
    deadlineDays: 21,
    deadlineText: "21 days after the tenancy ends (or 5 days after you leave due to condemnation).",
    penaltyText: "in bad faith owes a penalty equal to the amount withheld, plus up to $500 in punitive damages.",
    multiplier: 2,
    interest: "Simple interest is required by statute.",
  },
  {
    slug: "mississippi", name: "Mississippi", abbr: "MS",
    statute: "Miss. Code §89-8-21",
    deadlineDays: 45,
    deadlineText: "45 days after the tenancy ends.",
    penaltyText: "owes $200 plus actual damages where the failure is willful.",
    multiplier: null,
  },
  {
    slug: "missouri", name: "Missouri", abbr: "MO",
    statute: "Mo. Rev. Stat. §535.300",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "is liable for twice the amount wrongfully withheld.",
    multiplier: 2,
    depositCap: "Two months' rent.",
    notes: ["You have the right to be present at the move-out inspection after reasonable notice."],
  },
  {
    slug: "montana", name: "Montana", abbr: "MT",
    statute: "Mont. Code §70-25-202",
    deadlineDays: 30,
    deadlineText: "10 days if there are no deductions; 30 days when deductions are claimed.",
    penaltyText: "forfeits the right to keep any portion of the deposit and can owe the tenant's attorney's fees.",
    multiplier: null,
    notes: ["No cleaning charge is allowed unless you got written notice of the cleaning condition and 24 hours to fix it."],
  },
  {
    slug: "nebraska", name: "Nebraska", abbr: "NE",
    statute: "Neb. Rev. Stat. §76-1416",
    deadlineDays: 14,
    deadlineText: "14 days after demand and delivery of possession.",
    penaltyText: "can owe the deposit plus damages up to one month's rent.",
    multiplier: null,
    depositCap: "One month's rent (plus a quarter-month pet deposit).",
    forwardingNote: "Make a written demand with your forwarding address — the statute runs from your demand.",
  },
  {
    slug: "nevada", name: "Nevada", abbr: "NV",
    statute: "Nev. Rev. Stat. §118A.242",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "in bad faith can owe the full amount due plus damages up to the entire deposit again.",
    multiplier: 2,
    depositCap: "Three months' rent.",
  },
  {
    slug: "new-hampshire", name: "New Hampshire", abbr: "NH",
    statute: "N.H. Rev. Stat. §540-A:7",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "is liable for twice the amount wrongfully withheld.",
    multiplier: 2,
    interest: "Interest is owed if the deposit was held for a year or more (on request).",
    depositCap: "One month's rent or $100, whichever is greater.",
  },
  {
    slug: "new-jersey", name: "New Jersey", abbr: "NJ",
    statute: "N.J. Stat. §46:8-21.1",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "is liable for double the amount wrongfully withheld, plus court costs and attorney's fees.",
    multiplier: 2,
    interest: "Interest or investment earnings on the deposit are required.",
    depositCap: "One and one-half months' rent.",
  },
  {
    slug: "new-mexico", name: "New Mexico", abbr: "NM",
    statute: "N.M. Stat. §47-8-18",
    deadlineDays: 30,
    deadlineText: "30 days after termination of the tenancy.",
    penaltyText: "forfeits the right to claim any deductions and is liable for court costs and attorney's fees.",
    multiplier: null,
    depositCap: "One month's rent on leases under a year.",
  },
  {
    slug: "new-york", name: "New York", abbr: "NY",
    statute: "N.Y. Gen. Oblig. Law §7-108",
    deadlineDays: 14,
    deadlineText: "14 days after you move out — with an itemized statement for any deduction.",
    penaltyText: "can owe punitive damages of up to twice the deposit where the violation is willful.",
    multiplier: 2,
    depositCap: "One month's rent.",
    notes: [
      "Missing the 14-day itemization forfeits the landlord's right to keep any of the deposit — a very strong lever.",
      "You're entitled to a move-out inspection offer beforehand, with a chance to cure issues.",
    ],
  },
  {
    slug: "north-carolina", name: "North Carolina", abbr: "NC",
    statute: "N.C. Gen. Stat. §42-52",
    deadlineDays: 30,
    deadlineText: "30 days; if damage can't be assessed yet, an interim accounting in 30 days and a final one within 60.",
    penaltyText: "forfeits the right to keep any portion of the deposit and can owe the tenant's attorney's fees.",
    multiplier: null,
    depositCap: "Two months' rent on leases longer than month-to-month.",
  },
  {
    slug: "north-dakota", name: "North Dakota", abbr: "ND",
    statute: "N.D. Cent. Code §47-16-07.1",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "in bad faith can owe up to three times the amount wrongfully withheld.",
    multiplier: 3,
    depositCap: "One month's rent (higher for pets or certain histories).",
    interest: "Interest is required if the tenancy lasted 9 months or more.",
  },
  {
    slug: "ohio", name: "Ohio", abbr: "OH",
    statute: "Ohio Rev. Code §5321.16",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends and you deliver a forwarding address.",
    penaltyText: "owes damages equal to the amount wrongfully withheld — doubling your recovery — plus attorney's fees.",
    multiplier: 2,
    forwardingNote: "Provide your forwarding address in writing; without it, the penalty provisions don't apply.",
  },
  {
    slug: "oklahoma", name: "Oklahoma", abbr: "OK",
    statute: "Okla. Stat. tit. 41, §115",
    deadlineDays: 45,
    deadlineText: "45 days after the tenancy ends and you make a written demand.",
    penaltyText: "faces civil liability for the amount due — and willful retention is a criminal misdemeanor under the statute.",
    multiplier: null,
    forwardingNote: "Send a written demand for the deposit — the statute requires it, and our letter satisfies it.",
  },
  {
    slug: "oregon", name: "Oregon", abbr: "OR",
    statute: "Or. Rev. Stat. §90.300",
    deadlineDays: 31,
    deadlineText: "31 days after the tenancy ends.",
    penaltyText: "is liable for twice the amount wrongfully withheld.",
    multiplier: 2,
    notes: ["Deductions require a written accounting; carpet cleaning and similar charges have specific limits."],
  },
  {
    slug: "pennsylvania", name: "Pennsylvania", abbr: "PA",
    statute: "68 Pa. Stat. §250.512",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends or you surrender the property.",
    penaltyText: "forfeits all deductions and is liable for double the deposit.",
    multiplier: 2,
    interest: "Interest is owed once a deposit has been held more than two years.",
    depositCap: "Two months' rent in year one; one month's rent after.",
    forwardingNote: "You must provide your new address in writing to claim the doubling penalty.",
  },
  {
    slug: "rhode-island", name: "Rhode Island", abbr: "RI",
    statute: "R.I. Gen. Laws §34-18-19",
    deadlineDays: 20,
    deadlineText: "20 days after the tenancy ends and you return the keys.",
    penaltyText: "is liable for twice the amount wrongfully withheld, plus attorney's fees.",
    multiplier: 2,
    depositCap: "One month's rent.",
  },
  {
    slug: "south-carolina", name: "South Carolina", abbr: "SC",
    statute: "S.C. Code §27-40-410",
    deadlineDays: 30,
    deadlineText: "30 days after termination and demand.",
    penaltyText: "forfeits the right to withhold any portion and is liable for the tenant's attorney's fees.",
    multiplier: null,
  },
  {
    slug: "south-dakota", name: "South Dakota", abbr: "SD",
    statute: "S.D. Codified Laws §43-32-6.1 & §43-32-24",
    deadlineDays: 14,
    deadlineText: "Two weeks to return the deposit; a written itemization within 45 days if you request one.",
    penaltyText: "in bad faith can owe up to $200 in punitive damages on top of the amount due.",
    multiplier: null,
    depositCap: "One month's rent (more only in special circumstances).",
  },
  {
    slug: "tennessee", name: "Tennessee", abbr: "TN",
    statute: "Tenn. Code §66-28-301",
    deadlineDays: 30,
    deadlineText: "No hard return deadline in the statute — but itemization duties are detailed, 30 days is the standard courts expect, and unclaimed deposits can be forfeited after 60 days.",
    penaltyText: "or ignores the itemization and accounting rules forfeits the right to keep the deposit.",
    multiplier: null,
    notes: ["The URLTA applies in counties over ~75,000 population (Nashville, Memphis, Knoxville, Chattanooga areas)."],
  },
  {
    slug: "texas", name: "Texas", abbr: "TX",
    statute: "Tex. Prop. Code §92.103",
    deadlineDays: 30,
    deadlineText: "30 days after you move out and give a forwarding address.",
    penaltyText: "in bad faith owes $100 plus three times the amount wrongfully withheld, plus attorney's fees (Tex. Prop. Code §92.109).",
    multiplier: 3,
    flatBonus: 100,
    forwardingNote: "The 30-day clock starts when you give your forwarding address in writing — send it immediately if you haven't.",
    notes: ["A landlord who keeps the deposit in bad faith is presumed to have acted in bad faith if nothing arrives within 30 days."],
  },
  {
    slug: "utah", name: "Utah", abbr: "UT",
    statute: "Utah Code §57-17-3",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends.",
    penaltyText: "and ignores a 5-day cure notice owes the full deposit, a $100 civil penalty, and court costs.",
    multiplier: null,
    flatBonus: 100,
    notes: ["Send the demand letter first — it functions as the required notice, and the penalty attaches 5 days later."],
  },
  {
    slug: "vermont", name: "Vermont", abbr: "VT",
    statute: "9 V.S.A. §4461",
    deadlineDays: 14,
    deadlineText: "14 days after you vacate (60 days for some seasonal rentals).",
    penaltyText: "is liable for double the amount plus attorney's fees where the failure is willful — and forfeits any right to deductions.",
    multiplier: 2,
  },
  {
    slug: "virginia", name: "Virginia", abbr: "VA",
    statute: "Va. Code §55.1-1226",
    deadlineDays: 45,
    deadlineText: "45 days after the tenancy ends.",
    penaltyText: "is liable for the amount due plus actual damages and reasonable attorney's fees.",
    multiplier: null,
    depositCap: "Two months' rent.",
    notes: ["You can request to be present at the move-out inspection, which must occur within 72 hours of delivery of possession."],
  },
  {
    slug: "washington", name: "Washington", abbr: "WA",
    statute: "Wash. Rev. Code §59.18.280",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends (extended from 21 days by 2023 amendments).",
    penaltyText: "forfeits the right to keep any portion, and intentional refusal can cost up to twice the deposit plus attorney's fees.",
    multiplier: 2,
    notes: ["Deductions for damage require documentation — estimates, invoices, or receipts must accompany the statement."],
  },
  {
    slug: "west-virginia", name: "West Virginia", abbr: "WV",
    statute: "W. Va. Code §37-6A-2",
    deadlineDays: 60,
    deadlineText: "60 days after the tenancy ends — or 45 days after a new tenant moves in, whichever is shorter.",
    penaltyText: "in bad faith owes an additional penalty of one and one-half times the amount wrongfully withheld.",
    multiplier: 1.5,
  },
  {
    slug: "wisconsin", name: "Wisconsin", abbr: "WI",
    statute: "Wis. Admin. Code ATCP §134.06",
    deadlineDays: 21,
    deadlineText: "21 days after you surrender the premises.",
    penaltyText: "faces double damages plus attorney's fees under Wis. Stat. §100.20(5) — one of the strongest tenant remedies in the country.",
    multiplier: 2,
    notes: ["Routine carpet cleaning cannot be deducted from a Wisconsin deposit — a common illegal deduction."],
  },
  {
    slug: "wyoming", name: "Wyoming", abbr: "WY",
    statute: "Wyo. Stat. §1-21-1208",
    deadlineDays: 30,
    deadlineText: "30 days after the tenancy ends, or 15 days after you provide a forwarding address — whichever is later (plus up to 30 more days if damage is deducted, with notice).",
    penaltyText: "forfeits the right to withhold and is liable for court costs — and the deposit clause of your lease controls no further deductions.",
    multiplier: null,
    forwardingNote: "Send your forwarding address in writing to start the clock.",
  },
];

export function getState(slug: string): StateLaw | undefined {
  return STATES.find((s) => s.slug === slug);
}

/** States with a statutory damages multiplier of 2× or better. */
export const PENALTY_STATE_COUNT = STATES.filter((s) => (s.multiplier ?? 0) >= 2).length;

export function multiplierLabel(s: StateLaw): string | null {
  if (!s.multiplier) return null;
  const m = s.multiplier === 1.5 ? "1.5" : String(s.multiplier);
  return `${m}×`;
}
